version: 2

sources:
  - name: staging
    # for big-query
    database: de-zoomcamp-413404
    schema: trips_data_all
    tables:
      - name: green_tripdata
      - name: yellow_tripdata

  # for postgres
  # - schema: 
